### PR TITLE
Deprecate version 9.4

### PR DESCRIPTION
**Pull request by pkubatrh**
Mention version 10 in the README

### CODE REVIEW

**Comment by praiskup** [comment]
Just check, should the generated content for 9.4 be removed or not?

**Comment by pkubatrh** [comment]
Iirc the `generate` script was written as to not keep archives of deprecated versions, same as before the `postgresql:generated` branch introduction. So that should be the expected behaviour.

**Comment by pkubatrh** [comment]
Seems like the 9.4 Dockerfiles were still generated even when the 9.4 version was not used in Makefile so I have removed the version from multispec as well.

**Comment by praiskup** [comment]
I think that's because the 9.4 is not auto-removed, because VERSIONS= is generated against "master" branch, not against "generated" branch (as it was in https://github.com/sclorg/postgresql-container-generated/blob/c382d83b97b12296af7136b5a696ab9c7bbfde69/update)

**Comment by praiskup** [comment]
Yeah, I was wrong ... it's really removed by the `rm -rf !(common|source|update)` instruction.  The problem seems to be dumped into the error output:
```
* 'git add --ignore-removal <pathspec>', which is the current default,
  ignores paths you removed from your working tree.

* 'git add --all <pathspec>' will let you also record the removals.
```

So the removals are probably not committed.

**Comment by pkubatrh** [comment]
Yeah, seems like that might be the issue. I will add the `--all` option to the update script then and rebase.

**Comment by pkubatrh** [comment]
Rebased to latest common scripts. Lets see if that makes the difference.

**Comment by pkubatrh** [comment]
One more rebase to get in https://github.com/sclorg/container-common-scripts/pull/89

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
[test]
@omron93, I tried to hot-fix RHEL's CI (let's see how it works), but since I guess CentOS CI is responsible for pushing - it has to be fixed too _before_ merging this.  I don't have access there AFAIK.

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
LGTM

**Comment by praiskup** [comment]
Generated branch is not in sync;  I'll try to fix the jenkins job and resubmit the push event.

**Pull request merged**
