### PR TITLE
run all openshift4 tests even when one fails

### PR DESCRIPTION
**Pull request by zmiklank**
[test-all]

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Comment by phracek** [comment]
@zmiklank Rebase please.

**Comment by zmiklank** [comment]
rebased.
[test-all]

**Comment by phracek** [comment]
Please rebase it.

**Comment by phracek** [comment]
As soon as PR is rebased then OpenShift 4 tests should be passing.

**Comment by zmiklank** [comment]
Rebased.
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
test-all]

**Comment by phracek** [comment]
[test-all]

**Review by phracek — APPROVED** [review]
Everything LGTM. Tests are passing and all GREEN again.

**Pull request merged**
