### PR TITLE
tests: Add image update test to run-openshift

### PR DESCRIPTION
**Pull request by pkubatrh**
This test case is just for same-version updates, not version to version+1.

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
This should be final now.

@praiskup @hhorak ptal

**Comment by praiskup** [comment]
Looks fine! Thanks.

**Comment by pkubatrh** [comment]
Thanks for review, merging.

**Pull request merged**
