### PR TITLE
create dir and set permissions in a single layer to work around aufs limitations

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/sclorg/postgresql-container/issues/116

@csrwng ptal

### CODE REVIEW

**Comment by hhorak** [comment]
Even if it's not clear to me why something like that might make the difference, I understand we need to get rid of fail. If this patch helps, LGTM.

**Comment by bparees** [comment]
@hhorak see https://github.com/sclorg/postgresql-container/issues/116#issuecomment-232845287

**Comment by csrwng** [comment]
@bparees it's still broken for me ... I believe because /var/lib/pgsql gets created in the previous layer

However, this works:
https://github.com/sclorg/postgresql-container/compare/master...csrwng:fix_aufs_perms?expand=1

**Comment by bparees** [comment]
updated, @csrwng ptal again

**Comment by csrwng** [comment]
LGTM
tested all versions on a Mac with Docker for Mac and they all work.

**Comment by bparees** [comment]
thanks @csrwng, will wait for tests to pass and then merge.

**Pull request merged**
