### PR TITLE
Add rhel9 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by yselkowitz** [comment]
@phracek the Fedora test failed but I don't see how that's related to the imagestreams.

**Comment by hhorak** [comment]
> @phracek the Fedora test failed but I don't see how that's related to the imagestreams.

It's not not related to imagestreams, it's due to missing `setfacl`, that was supposed to be fixed by https://github.com/sclorg/sclorg-testing-farm/commit/ef7038912e0f4d686c36ee386febe017fc4d3d00, but it's still not entirely. @phracek what else do we need to do to have the acl package installed on the Fedora host?

**Comment by hhorak** [comment]
Not related to these changes, but I've realized the `13-el7` tag was in the imagestream twice. https://github.com/sclorg/postgresql-container/pull/445 removes it, I'd appreciate double-check.

**Pull request merged**
