### PR TITLE
Add distgen generated files

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds dist-gen generated files to upstream.
As the same approach has s2i-python-container and varnish-container.

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by pkubatrh** [comment]
Lets merge this after #457 is done. Or I can just generate the files in the other PR I guess?

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Pull request merged**
