### PR TITLE
Remove code duplications in set_pgdata

### PR DESCRIPTION
**Pull request by kaasasolut**

### CODE REVIEW

**Comment by praiskup** [comment]
This looks fine, thanks!  It would be nice to fix other versions too (not only 9.5). @kaasasolut are you able to take a look at this? [test]

**Comment by kaasasolut** [comment]
Done.

**Comment by praiskup** [comment]
Looks fine to me, can we merge this, please? [test]

**Comment by kaasasolut** [comment]
Yes, of course.

**Comment by omron93** [comment]
Merging. @kaasasolut Thanks for the fix.

**Pull request merged**
