### PR TITLE
remove force tag flag

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by praiskup** [comment]
Is it guaranteed that double-`make test` hit wont generate the same tag now?  Or what is the reasoning underneath?  The comment above fixed command still says "Re-tagging ...".

**Comment by praiskup** [comment]
Sorry, @bparees ^^?

**Comment by bparees** [comment]
@praiskup docker 1.12 doesn't throw an error if you tag something w/ a tag that already exists, it just overwrites it:

```
[ec2-user@ip-172-18-10-100 ~]$ docker version
Client:
 Version:         1.12.2-rc2
 API version:     1.24
 Package version: docker-common-1.12.2-5.el7.x86_64
 Go version:      go1.6.2
 Git commit:      19dbe35
 Built:           Mon Oct 17 11:44:51 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.2-rc2
 API version:     1.24
 Package version: docker-common-1.12.2-5.el7.x86_64
 Go version:      go1.6.2
 Git commit:      19dbe35
 Built:           Mon Oct 17 11:44:51 2016
 OS/Arch:         linux/amd64

[ec2-user@ip-172-18-10-100 ~]$ docker tag registry.access.redhat.com/rhel7.1 test1

[ec2-user@ip-172-18-10-100 ~]$ docker tag docker.io/centos test1

[ec2-user@ip-172-18-10-100 ~]$ docker images | grep docker.io/centos
docker.io/centos                         centos7             980e0e4c79ec        8 weeks ago         196.7 MB
docker.io/centos                         latest              980e0e4c79ec        8 weeks ago         196.7 MB

[ec2-user@ip-172-18-10-100 ~]$ docker images | grep test1
test1                                    latest              980e0e4c79ec        8 weeks ago         196.7 MB
```

**Comment by praiskup** [comment]
Thanks, interesting (but it's worth telling in the commit message, too).  I still have docker 1.10 on my box (Fedora 24), and seems like in the RHEL7 CI there's 1.9 only (missing `--ip` flag) so I'm curious whether it's not too soon for this change.

**Comment by praiskup** [comment]
I can see the `Warning: '-f' is deprecated, it will be removed soon. See usage.` message on 1.10.  So it's probably not at least for me :).  And the RHEL CI should be updated then.

**Pull request merged**
