### PR TITLE
Add support for the latest postgresql-15 imagestreams.

### PR DESCRIPTION
**Pull request by phracek**
Add support for the latest postgresql-15 imagestreams.

Allow also testing them as they reached GA.

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test]

**Comment by phracek** [comment]
[test-all]

**Review by zmiklank — APPROVED** [review]
LGTM, thanks. I would suggest to squash the commits though.

**Pull request merged**
