### PR TITLE
Remove duplicit 13-el7 tag

### PR DESCRIPTION
**Pull request by hhorak**
The tag was in the image stream twice

### CODE REVIEW

**Comment by hhorak** [comment]
[test-all]

**Comment by hhorak** [comment]
[test]

**Comment by yselkowitz** [comment]
LGTM, thanks for catching that.

**Review by phracek — APPROVED** [review]
LGTM. Thanks for the PR. As soon as common submodule is rebased and tests are passing, we can merge it.

**Comment by hhorak** [comment]
[test]

**Pull request merged**
