### PR TITLE
 add example for enabling ssl connections

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
seems like some timeout happened during rhel8 tests, trying once more
[test]

**Comment by pkubatrh** [comment]
@phracek Can you take a quick look at this PR?

**Comment by phracek** [comment]
Definitely. I will do it.

**Comment by phracek** [comment]
Based on the documentation https://www.postgresql.org/docs/9.6/app-psql.html test looks good to me.

LGTM.

**Comment by phracek** [comment]
I am missing only documentaion about SSL. But this can be solved in the other pull request

**Comment by phracek** [comment]
https://github.com/sclorg/postgresql-container/issues/345

**Comment by pkubatrh** [comment]
Thanks for review! Tests are green, so merging.

**Comment by pkubatrh** [comment]
Now that I am looking closely on the test case during working on an unrelated issue I wonder how the CI did not manage to fail when the function to run the test is called `run_s2i_ssl_enable_test` but the `TEST_LIST` entry is called `run_s2i_enable_ssl_test` ...

**Comment by pkubatrh** [comment]
The masked failure should be fixed by https://github.com/sclorg/container-common-scripts/pull/125

**Pull request merged**
