### PR TITLE
Adding instructions and changes in the enable-ssl example

### PR DESCRIPTION
**Pull request by mrbrandao**
Those changes improves and provide examples on how to use the `examples/enable-ssl` in OpenShift  

+ Changing the example secrets to a separated directory from `enable-ssl/server*` to `enable-ssl/certs/tls*`   
_This allows user to mount their keys in a single directory without having
   to mount secrets on top configurations file in `/opt/app-root/src`_
   e.g:
  ```bash
    oc set volume --add --type=secret --secret-name mysecret \
    --mount-path /opt/app-root/src/tls --default-mode 0640 dc/myapp
  ```
+ Removing `chmod` command from the pre-start script   
 _Certs are better to be mounted in OpenShift with the proper
    permissions already set from the `pod.spec.volumes.secret.defaultMode`_
+ This also fix the fail bellow.   
_When using the deployment in OpenShift without anyuid scc the following error was ocurring with:_  
    ```
    => sourcing /opt/app-root/src/postgresql-pre-start/enable_ssl.sh ...
    chmod: changing permissions of 'server.key': Operation not permitted
    ```
+ Moved `server.key` and `server.crt` to the new `certs` directory  
+ Added a README instruction file

### CODE REVIEW

**Comment by Lupphes** [comment]
LGTM. I will extend the documentation with my notes when this PR is merged.
@mrbrandao Do you have some minimal OpenShift configuration for your example that you could include?

**Comment by fila43** [comment]
@mrbrandao thank you for your contribution. I will merge it as the tests passed.

**Comment by fila43** [comment]
[test-all]

**Comment by fila43** [comment]
[test-all]

**Comment by mrbrandao** [comment]
Hello @Lupphes I see the `TESTS="run_s2i_enable_ssl_test"` is failing.  I can fix with:

```
-# chmod og-rwx server.key
+chmod og-rwx certs/*.key
```

however this will fail in openshift :
```
    => sourcing /opt/app-root/src/postgresql-pre-start/enable_ssl.sh ...
    chmod: changing permissions of 'server.key': Operation not permitted
```

do you have any suggestion? Perhaps we can leave the pre-start script but try to skip it when using a `oc new-app`.
Let me know your thougths.

Thank you

**Comment by mrbrandao** [comment]
I've just updated with a fix to the `run_s2i_enable_ssl_test` also improved the README, by adding examples on how to use with `restriced` and `anyuid` scc. 
Let me know if looks better now. Thank you

**Comment by fila43** [comment]
[test-all]

**Comment by fila43** [comment]
[test-all]

**Comment by fila43** [comment]
There are weird test-case (Openshift 4) fails. Unfortunately, I am not an expert in this area. @phracek PTAL.

**Comment by phracek** [comment]
[test-all]

**Comment by fila43** [comment]
[test-all]

**Comment by fila43** [comment]
The majority of tests passed. Openshift 4 test failed due to connection issues: `Error: Failed to download metadata for repo 'rhel-9-server-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried`
RHEL8 tests failed due to a broken test `run_master_restart_test`
So I see it as LGTM and ready to merge.

**Review by fila43 — APPROVED** [review]

**Pull request merged**
