### PR TITLE
Remove streams that will be soon EOL.

### PR DESCRIPTION
**Pull request by hhorak**
With no el7 based 9.6 stream, we do not need a separate imagestream for ppc64le and s390x eiter.

### CODE REVIEW

**Comment by hhorak** [comment]
@yselkowitz @phracek @pkubatrh WDYT?

**Comment by yselkowitz** [comment]
LGTM, but any explanation for the test failures?

**Comment by hhorak** [comment]
> LGTM, but any explanation for the test failures?

We experienced some CI issues, let's try again.
[test-openshift][test]

**Comment by hhorak** [comment]
[test-openshift][test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
We still didn't convince Jenkins to work properly, so I verified manually that the imagestream is valid. Merging.

**Pull request merged**
