### PR TITLE
Deprecated EOL 9.6 postgresql image

### PR DESCRIPTION
**Pull request by phracek**

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
Locally RHEL7 - OpenShift 4 passed. Let's try one more time

[test-openshift]

**Comment by phracek** [comment]
Locally RHEL7 - OpenShift 4 passed. Let's try one more time

[test-openshift]

**Comment by phracek** [comment]
Locally RHEL7 - OpenShift 4 passed. Let's try one more time

[test-openshift]

**Comment by phracek** [comment]
The `CentOS 7 - OpenShift 3` test failed for reason - OpenShift does not start.

```bash
I0207 11:04:38.359311   22307 interface.go:41] Finished installing "centos-imagestreams" "openshift-router" "sample-templates" "openshift-image-registry" "persistent-volumes" "openshift-web-console-operator"
Error: timed out waiting for the condition
+ ct_os_cleanup
+ echo ''

+ '[' 0 -eq 0 ']'
OpenShift tests for quay.io/centos7/postgresql-13-centos7:1 succeeded.
+ echo 'OpenShift tests for quay.io/centos7/postgresql-13-centos7:1 succeeded.'
make: *** [test-openshift] Error 1
```

But this test does not block this pull request.

**Comment by fila43** [comment]
although I am not so experienced in problematic of multispec.yml I didn`t spot any issue.

**Pull request merged**
