### PR TITLE
Improve the documentation on mounted directory permissions

### PR DESCRIPTION
**Pull request by strzibny**
I just came across this (even opened and closed an issue because of that) and feel like this should be mentioned.

### CODE REVIEW

**Comment by mnagy** [comment]
Hmm, not sure what to do with this one. Close?

**Comment by bparees** [comment]
@mnagy I think it's a good thing to note though it should be clearer that it's referring to setting permissions in the host directory that you are bind mounting into the container for db storage. 

That said, I think we should let the scl team decide how to proceed with documenting it at this point. @praiskup.  The permissions need to at least ensure  the container uid can read/write the dir.

**Comment by praiskup** [comment]
Well, are we talking about OpenShift environment, or regular 'docker run' use-case?

In the first case, OpenShift should take care of it, in the letter I would prefer something like
https://github.com/devexp-db/cont-postgresql/blob/master/share/cont-docs/postgresql/HOME.txt.tpl#L48
I bet I have a typo there however, there should be 'setfacl -m u:26:rwx' probably.

**Comment by praiskup** [comment]
It is not a typo.

**Comment by bparees** [comment]
@praiskup yes this is only relevant to manual docker run, all the more reason I defer to the SCL team.

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Pull request closed without merging**
