### PR TITLE
Move test latest_imagestreams into openshift tests

### PR DESCRIPTION
**Pull request by phracek**
Move test latest_imagestreams into openshift tests.
Update container-common-scripts into the latest.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
Let's try one more time

[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
Tests fail because of postresql-9.6 is deprecated. EOL PR is here: https://github.com/sclorg/postgresql-container/pull/391

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift][test-openshift-4]

**Comment by pkubatrh** [comment]
lgtm, thanks!

**Pull request merged**
