### PR TITLE
New generator written in Python

### PR DESCRIPTION
**Pull request by frenzymadness**
The common submodule has to be updated here as well after we merge https://github.com/sclorg/container-common-scripts/pull/294

I did some cleanup of useless files detected when I used the new generator for the first time.

### CODE REVIEW

**Comment by frenzymadness** [comment]
For the details about removing targets from Makefile see this comment: https://github.com/sclorg/container-common-scripts/pull/294#issuecomment-1265321660

**Comment by frenzymadness** [comment]
Please, review this PR so I can merge it after the update of the common scripts.

**Review by zmiklank — APPROVED** [review]
LGTM, thank you.

If you would like to you can remove generating of `cccp.yml`. If not, I will handle that sometime later :).

**Comment by frenzymadness** [comment]
> If you would like to you can remove generating of `cccp.yml`. If not, I will handle that sometime later :).

Done. Thanks a lot for the review.

**Pull request merged**
