### PR TITLE
Change RH required labels based on updated spec

### PR DESCRIPTION
**Pull request by hhorak**
For full spec, see https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by hhorak** [comment]
The new labels are not yet available in OSBS, so closing this PR for now and we'll probably change this in *all* images once it will be the right time.

**Pull request closed without merging**
