### PR TITLE
[run-postgresql] Make the DB initialization atomic

### PR DESCRIPTION
**Pull request by iankko**
(complete all of its parts or retry it if some failed)

Might possibly fix: https://github.com/sclorg/postgresql-container/issues/309 (Didn't test it though)

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

### CODE REVIEW

**Comment by praiskup** [comment]
That variable is always false at that point.

**Comment by iankko** [comment]
Closing, this will need to be redone yet based on the discussion in the original issue.

**Comment by iankko** [comment]
Yet, re: _That variable is always false at that point._ - that was actually the intention. Always try to retry the DB init if the variable isn't set to something else than _"false"_ yet. AFAICT this should be safe (if the DB entry already exists, calling next DB init won't touch it). 

But the problem is, if not the whole DB initialization process finished before, the missing phases won't be retried in the 2nd run :(.

**Comment by praiskup** [comment]
> AFAICT this should be safe (if the DB entry already exists, calling next DB init won't touch it).

But re-initdb would fail, and that would fail the whole script/container run.

**Pull request closed without merging**
