### PR TITLE
Add support for building, testing and pushing postgresql-15

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for building, testing Postgresql-15.

Push to the quay.io/fedora registry is already part of this pull request.

The quay.io/fedora/postgresql-15 already exists https://quay.io/repository/fedora/postgresql-15?tab=info

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Pull request merged**
