### PR TITLE
disable testing and pushing to quay.io for CentOS7 image

### PR DESCRIPTION
**Pull request by zmiklank**
and migrate from f35 to f37 for fedora images, as f35 is now EOL

### CODE REVIEW

**Comment by zmiklank** [comment]
This is WIP.

[test-all]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
@pkubatrh not sure, how to deal with centos7 containerfiles in distgen-generated containers. Is it enough to disable testing and pushing, like it is done in this PR?
Or should the centos7 containerfiles be also removed from the distgen matrix?

**Review by phracek — CHANGES_REQUESTED** [review]
Fedora tests are failing and we need to fix it. Although it is not related to this pull rquest.

**Comment by phracek** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
> Fedora tests are failing and we need to fix it. Although it is not related to this pull rquest.

It is problem on rpm level. This rpm update should fix it:
https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2023-e6d66cd1a4

**Comment by pkubatrh** [comment]
> not sure, how to deal with centos7 containerfiles in distgen-generated containers. Is it enough to disable testing and pushing, like it is done in this PR?
Or should the centos7 containerfiles be also removed from the distgen matrix?

That is a tricky question. Is it possible to keep generating all the files needed for centos7 images, but add .exclude file generation on top of that, or would that be too much complexity?

**Comment by zmiklank** [comment]
> > not sure, how to deal with centos7 containerfiles in distgen-generated containers. Is it enough to disable testing and pushing, like it is done in this PR?
> > Or should the centos7 containerfiles be also removed from the distgen matrix?
> 
> That is a tricky question. Is it possible to keep generating all the files needed for centos7 images, but add .exclude file generation on top of that, or would that be too much complexity?

IMO too much complexity for the first of deprecation steps. But a feasible way could be to keep the centos7 config files for distgen and only add centos7-exclude rule to the exclude matrix in [here](https://github.com/sclorg/postgresql-container/blob/89dc0b255fc713f9a47ac31ac2a6cf5436d88c62/specs/multispec.yml#L160). That way would be really easy to enable their generation again if someone requests it.

**Comment by pkubatrh** [comment]
>But a feasible way could be to keep the centos7 config files for distgen and only add centos7-exclude rule to the exclude matrix in [here](https://github.com/sclorg/postgresql-container/blob/89dc0b255fc713f9a47ac31ac2a6cf5436d88c62/specs/multispec.yml#L160). That way would be really easy to enable their generation again if someone requests it.

Agreed, I wanted to suggest exactly this if we did not want to add creation of exclude files. So keeping the sources while also not generating the result for centos7 is ok as far as I am concerned.

**Comment by zmiklank** [comment]
[test]

**Comment by phracek** [comment]
> @pkubatrh not sure, how to deal with centos7 containerfiles in distgen-generated containers. Is it enough to disable testing and pushing, like it is done in this PR?
> Or should the centos7 containerfiles be also removed from the distgen matrix?

I would only remove testing and pushing image from TFAGA. The users should have still possibility to use CentOS 7 images. But this is only my opinion.

**Comment by zmiklank** [comment]
> > @pkubatrh not sure, how to deal with centos7 containerfiles in distgen-generated containers. Is it enough to disable testing and pushing, like it is done in this PR?
> > Or should the centos7 containerfiles be also removed from the distgen matrix?
> 
> I would only remove testing and pushing image from TFAGA. The users should have still possibility to use CentOS 7 images. But this is only my opinion.

In theory they still can. They can take the Dockerfile from git history. Or remove centos7 from exclude matrix and generate the Dockerfile locally.

**Comment by zmiklank** [comment]
It looks like we'll need to wait for the postgres fix a bit longer.

**Comment by pkubatrh** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
Tests for `Testing Farm - Fedora - 14` failed - problem is missing pgaudit in module of postresql:14 in Fedora 38. Fix is on its way on RPM level.

**Comment by zmiklank** [comment]
I am not sure if we ever merge this PR :D.
Now the Testing Farm crashes on Fedora:
`[31m[06:33:36] [E] [Fedora-latest:x86_64:/plans/fedora/test-ci] guest provisioning failed: Guest couldn't be provisioned: Artemis resource ended in 'error' state[0m`

**Review by pkubatrh — APPROVED** [review]
Version 14 on Fedora tested locally and is green. LGTM

**Pull request merged**
