### PR TITLE
Add support for running PostgreSQL container using atomic tool

### PR DESCRIPTION
**Pull request by hhorak**
This support will struggle with same issues as mysql's ones, at least for usability PoV.
@praiskup what do you think?

### CODE REVIEW

**Comment by hhorak** [comment]
hm, will need to rebase..

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Comment by hhorak** [comment]
No good use case for `atomic run` to be much better than `docker run`, closing.

**Pull request closed without merging**
