### PR TITLE
Add example how to enable extension

### PR DESCRIPTION
**Pull request by hhorak**
TODO: This would deserve a test as well.

### CODE REVIEW

**Comment by fridex** [comment]
Thanks, @hhorak! :+1:

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by mscherer** [comment]
Wouldn't it be better for users to have environment variables for that ? For example, if a user want to enable hstore, shipped by default, having to do a separate container is a bit annoying, while it could be done with a variable POSTGRES_EXTENSIONS, who would run CREATE IF NOT EXISTS at start on all extensions in the list (either space separated, or comma separated, whatever is the most consistent with others containers).

**Comment by mscherer** [comment]
So I went ahead with #399 (with tests and docs).

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by fila43** [comment]
[test]

**Comment by phracek** [comment]
@hhorak Please generate also source via distgen. Let's get test it and merge it. Generated sources are outdated.

**Comment by hhorak** [comment]
Rebased.

**Review by phracek — APPROVED** [review]
LGTM. THanks for PR and also README.

**Pull request merged**
