### PR TITLE
new-common scripts

### PR DESCRIPTION
**Pull request by praiskup**
Fix: #255

### CODE REVIEW

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
Seems like centos7 CI has some problems to spawn OpenShift cluster.

**Comment by praiskup** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
For the rhel failure I think this is caused by tagging the wrong image into the imagestream (since it also does not use the :latest tag)

https://github.com/sclorg/postgresql-container/blob/master/test/run-openshift#L170

**Comment by praiskup** [comment]
@pkubatrh yes, thanks :-) let's see now.

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
There's (or was) some race in RHEL7 CI.  Centos7 CI is broken, but that's not related to this PR. PTAL

**Comment by praiskup** [comment]
Let's give the centos CI another chance [test-openshift].

**Comment by praiskup** [comment]
This drives me crazy https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-postgresql-rh-openshift/80/consoleText

Btw. imagestreams seem to reference :latest tag too, so I'm curious whether we have guarantees that the right image gets downloaded...  beer to anyone who first writes here where the race is... :-)
```
+ docker pull registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest
Trying to pull repository registry.access.redhat.com/rhscl/postgresql-96-rhel7 ... 
latest: Pulling from registry.access.redhat.com/rhscl/postgresql-96-rhel7
9a32f102e677: Already exists
b8aa42cec17a: Already exists
a73c034266f6: Already exists
9f4cf1f3fc1e: Pulling fs layer
9f4cf1f3fc1e: Verifying Checksum
9f4cf1f3fc1e: Download complete
9f4cf1f3fc1e: Pull complete
Digest: sha256:8837530839f3e0db75c0cfc435952c031d3010d1032168535698b5def13b6b68
```

**Comment by omron93** [comment]
There is similar dis-synchronization for `registry.access.redhat.com/rhscl/s2i-core-rhel7` in CI OpenStack (release 14, instead of 15, the postgresql image uses same layers). There must be some cache or something similar deployed there...

**Comment by omron93** [comment]
It must be connected with the OpenStack. I tried same on centos VM and get the same wrong image...

**Comment by praiskup** [comment]
[test-openshift] it seems to work now, but OTOH the fix is imo not working...

**Comment by pkubatrh** [comment]
>There must be some cache or something similar deployed there...

Seems likely. We hit the issue again today so I could take a more detailed look and from what I can see the docker daemon is fed old metadata it is trying to get from the registry. For example the latest manifest [1] has different content when fetched inside the Openstack instance.

[1] https://registry.redhat.io/webassets/docker/content/dist/rhel/server/7/7Server/x86_64/rhscl/1/containers/registry/rhscl/postgresql-96-rhel7/manifests/1/latest

**Comment by praiskup** [comment]
Closing in favor of #267.

**Pull request closed without merging**
