### PR TITLE
tests: Add replication test to run-openshift

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by hhorak** [comment]
Really nice work, I haven't spotted any obvious issue, feel free to merge.

**Comment by praiskup** [comment]
Looks fine, thanks!

**Comment by pkubatrh** [comment]
Thanks for review, meging.

**Pull request merged**
