### PR TITLE
Adding server started message to run scripts

### PR DESCRIPTION
**Pull request by coreydaley**
Adding server started message to run scripts
since the last message displayed is always
server stopped which can be confusing for users

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees ptal

**Comment by pkubatrh** [comment]
This message will never get printed out as the shell execs into `postgres` right before it ...

**Comment by coreydaley** [comment]
@pkubatrh Whoops, I'll move the message before the exec and repush.  thanks

**Comment by coreydaley** [comment]
@pkubatrh patch updated, ptal

**Comment by bparees** [comment]
I probably would have gone w/ "Starting server..." (and i'm curious why we get no stdout from the server when it starts?) but this is fine.

**Comment by coreydaley** [comment]
@bparees updated

**Comment by pkubatrh** [comment]
Yes, "starting server" makes more sense, thanks! lgtm [test]

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
Merging, thanks!

**Pull request merged**
