### PR TITLE
Add tests for verifying postgresql image in a remote OpenShift cluster

### PR DESCRIPTION
**Pull request by hhorak**
This adds a new make option `make test-openshift-remote-cluster` that runs `test/run-openshift-remote-cluster` and it runs the test within a remote OpenShift cluster. It requires `oc` command to exist and being logged in in a working cluster. The same functions are also added into `run-openshift` script, so those are tested during PR tests.

### CODE REVIEW

**Comment by hhorak** [comment]
[test-openshift]

**Comment by hhorak** [comment]
BTW this PR requires also a change in container-common-scripts: https://github.com/sclorg/container-common-scripts/pull/108/files

@praiskup @pkubatrh WDYT? I'd like to create a similar PR for other container images, but would like to see whether it is the correct way to do it first.

**Comment by praiskup** [comment]
Looks like just file removal, and adding one new test which is possible to run against local or remote OpenShift cluster. If I interpret that correctly, it sounds wise - we should move as many tests as possible into the "common" tests subset... LGTM.

**Comment by hhorak** [comment]
Yes, it is exactly that. We might move the rest or the functions as well, although I doubt they will "just work" on remote cluster as they are written now. It will probably need some more adjustments,  that I did not try yet. Merging now, and a new issue reported to track the porting of rest of the tests as #311.

**Comment by praiskup** [comment]
thanks

**Pull request merged**
