### PR TITLE
Bump rhel 7 minor version

### PR DESCRIPTION
**Pull request by praiskup**
find -name Dockerfile.rhel7 -exec sed -i 's/^FROM rhel7.2/FROM rhel7.3/' {} +

### CODE REVIEW

**Comment by praiskup** [comment]
@anybody, could we switch back to "FROM rhel7"?

**Comment by bparees** [comment]
if possible it would be my preference.  the openshift CI infrastructure has to construct a mocked up rhel7.x image, so if you change this, our infrastructure will have to change to use the rhel7.3 tag when constructing the mock image.

**Comment by bparees** [comment]
[test] (to demonstrate the failure on the openshift CI)

**Comment by praiskup** [comment]
@hhorak, does that sound wise?

**Comment by hhorak** [comment]
Yes, I think `FROM rhel7` will be better.

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
PTAL

**Comment by hhorak** [comment]
LGTM. @bparees does openshift CI infrastructure need some change for the `FROM rhel7` case as well? Or can we merge now?

**Comment by bparees** [comment]
i've made the CI changes, i think we're ok to merge.
curious why my [test] tag got ignored though.

**Comment by bparees** [comment]
(the test will still fail as the changes are working their way through, but i won't hold you guys up on that, you can merge if you're ready)

**Comment by hhorak** [comment]
Merged.

**Pull request merged**
