### PR TITLE
Support PostgreSQL 14 on Fedora

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for building, testing, and pushing PostgreSQL-14 container on Fedora.

- source files contains version 14
- build-and-push action contains Fedora quay.io enablement for pushing
- main README.md file is updated
- dist-gen generated files are added as well.

### CODE REVIEW

**Comment by phracek** [comment]
@fila43 @hhorak @zmiklank Please review it. It has to be merged after #496 .

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
I would like to only test if OpenShift is working

[test-openshift]

**Comment by phracek** [comment]
I would like to only test if OpenShift is working

[test-openshift]

**Comment by phracek** [comment]
OpenShift 4 tests are fixed by #499

**Comment by phracek** [comment]
OpenShift is not related. Do not execute tests.

[test]

**Comment by phracek** [comment]
OpenShift is not related. Do not execute tests.

[test]

**Review by pkubatrh — APPROVED** [review]

**Pull request merged**
