### PR TITLE
document permissions for bind-mounted host directories

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
Is the spelling/place OK?  I would fix the 9.5 and 9.4 versions too...

**Comment by omron93** [comment]
LGTM, thanks.

**Comment by pkubatrh** [comment]
>Can somebody merge this, then?

Is this ready for a merge? I thought you wanted to make some changes to previous versions as well.

**Comment by praiskup** [comment]
Meh, you are right.  Sorry.

**Comment by omron93** [comment]
Thanks. Tests are passing, so merging.

**Pull request merged**
