### PR TITLE
Recover database before trying to upgrade using `pg_upgrade`

### LINKED ISSUE #469: Upgrading fails if previous shutdown of database was not clean
If the last shutdown of the database was not clean and a recovery of the database is necessary on startup, the `pg_upgrade` will fail.

This can be solved by booting up the old (previous) postgres server and stop it properly before the migration with `pg_upgrade` is triggered.

### PR DESCRIPTION
**Pull request by robertaistleitner**
This fixes #469

### CODE REVIEW

**Comment by hhorak** [comment]
This idea looks good to me, thanks for the contribution. I'll rebase the PR.

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by fila43** [comment]
It seems to be LGTM. `run_master_restart_test` fails regardless of the proposed changes and other failures seem to be caused by infrastructure.

**Comment by fila43** [comment]
[test]

**Comment by fila43** [comment]
Tests randomly fail with `Failed to download metadata for repo 'rhel-8-server-appstream-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1` @phracek have you ever seen it? Or do you have any idea how to fix it please?

**Review by fila43 — APPROVED** [review]

**Comment by fila43** [comment]
All tests passed except one `run_master_restart_test` unrelated to the upgrade and it fails randomly.

**Pull request merged**
