### PR TITLE
Add RHEL8 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by phracek** [comment]
@yselkowitz These imagestreams should be deleted https://github.com/sclorg/postgresql-container/blob/master/imagestreams/postgresql-rhel7-ppc64le.json, https://github.com/sclorg/postgresql-container/blob/master/imagestreams/postgresql-rhel7-s390x.json, right? Can you please do it in this pull request, like for the others.

**Comment by yselkowitz** [comment]
If I could have, I would have.  They cannot be removed at this time because 9.6 is still supported on x86_64 but was never containerized (for RHEL 7) on P&Z.

**Comment by hhorak** [comment]
Thanks for the PR, LGTM.

**Comment by hhorak** [comment]
Image stream verified manually.

**Pull request merged**
