### PR TITLE
Add postgresql version 9.6

### PR DESCRIPTION
**Pull request by pkubatrh**
Uses https://github.com/sclorg/container-common-scripts/pull/20 . Should not be merged until this PR is merged.

Packages for 9.6 not yet available so the build has been disabled for this version for now.

### CODE REVIEW

**Comment by pkubatrh** [comment]
Pulled in newest container-common-scripts.

**Comment by praiskup** [comment]
We can't build 9.6 image at all, which is expected probably.  Otherwise it looks good to me.

**Comment by praiskup** [comment]
Ah, `git grep 95 latest` and `git grep 9.5 latest` don't give me empty output yet.

**Comment by praiskup** [comment]
What about to have `TARGET=f26_copr` for `Dockerfile.f26_copr`; and install packages from https://copr.fedorainfracloud.org/coprs/g/db-sig/sclo-postgresql96 ?

**Comment by pkubatrh** [comment]
>Ah, git grep 95 latest and git grep 9.5 latest don't give me empty output yet.

Right, since the README was changed after the PR was created. Will make sure it uses correct versions.

**Comment by pkubatrh** [comment]
> edit: maybe rather TARGET=fedora_copr to allow us to have only one fedora dockerfile till we have some templating system on place ...

Might be better to just use the regular fedora target for this (for now), since we do not have a fedora Dockerfile for 9.6 yet anyway. And this way we would not need to make any additional changes to the common scripts until we know what kind of templating system to use in future.

**Comment by praiskup** [comment]
Per @hhorak 's note, the rh-postgresql96 packages already live here:
https://cbs.centos.org/repos/sclo7-rh-postgresql96-rh-candidate/x86_64/os/

Perhaps we could enable the repository temporarily to have at least one container built.  @pkubatrh WDYT?

**Comment by praiskup** [comment]
Without paying too much attention to the patch, this did the trick for me:
```patch
 RUN yum install -y centos-release-scl-rh && \
+    yum-config-manager --add-repo https://cbs.centos.org/repos/sclo7-rh-postgresql96-rh-candidate/x86_64/os/ && \
+    echo gpgcheck=0 >> /etc/yum.repos.d/cbs.centos.org_repos_sclo7-rh-postgresql96-rh-candidate_x86_64_os_.repo && \
     INSTALL_PKGS="rsync tar gettext bind-utils rh-postgresql96 rh-postgresql96-postgresql-contrib nss_wrapper" && \
```

**Comment by praiskup** [comment]
Otherwise looks good now, thanks.

**Comment by pkubatrh** [comment]
Good idea, thanks. I have enabled the centos7 build with testing rpms

**Comment by pkubatrh** [comment]
[test]

**Comment by praiskup** [comment]
LGTM

**Comment by pkubatrh** [comment]
Tests are passing now, merging. Thanks for review

**Pull request merged**
