### PR TITLE
Support c9s building testing pushing

### PR DESCRIPTION
**Pull request by phracek**
This pull requests adds support for building, testing and pushing postgresql-container with CentOS Stream 9

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
This https://github.com/sclorg/container-common-scripts/pull/230 needs to be merged before merging this pull request.

**Comment by phracek** [comment]
[test-all]

**Comment by fila43** [comment]
Changes make sense to me, but I Am not an expert in the build and push area.

**Comment by phracek** [comment]
@fila43 thanks. Review only `manifest.sh`, `spec/multispec.yml` and, `src/Dockerfile` is needed.

**Pull request merged**
