### PR TITLE
common: move to latest version

### PR DESCRIPTION
**Pull request by praiskup**
- VERSION make variable is not used now
- help.1 is auto-generated (to mimic osbs behavior)

### CODE REVIEW

**Comment by pkubatrh** [comment]
lgtm. The CI does not seem to cooperating though...

**Comment by praiskup** [comment]
@pkubatrh CI doesn't seem to complain now. Thanks for the review, btw!

**Comment by pkubatrh** [comment]
The centos CI doesnt seem to have started up. I have tested this PR on a centos machine manually and no problems encountered.

Merging.

**Comment by praiskup** [comment]
Thanks!

**Pull request merged**
