### PR TITLE
fast-forward the 'common' sub-project

### PR DESCRIPTION
**Pull request by praiskup**
This is to fix build-system regression
https://github.com/sclorg/container-common-scripts/pull/60

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift] two different issues in both CIs?
https://ci.centos.org/job/SCLo-container-postgresql-rh-openshift/38/
https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-postgresql-rh-openshift/39/

**Comment by omron93** [comment]
> two different issues in both CIs?

Both connected to getting IP of slave. `oc` versions are different in RHEL (`oc v3.6.173.0.83`) and CentOS (`oc v3.7.0+7ed6862`), so this could cause the difference in the output.

**Comment by pkubatrh** [comment]
Seems like the first failures that got squashed were introduced in #233

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
I've added some description for the test fix, [test-openshift]

**Comment by praiskup** [comment]
[test-openshift] (random fail? https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-postgresql-rh-openshift/42/)

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
[test-openshift] https://ci.centos.org/job/SCLo-container-postgresql-rh-openshift/43/

**Comment by praiskup** [comment]
[test-openshift]

**Comment by praiskup** [comment]
PTAL, should be ready.

**Comment by praiskup** [comment]
[test-openshift] last time, now with 4GB of ram

**Comment by omron93** [comment]
LGTM. Small changes...

@praiskup Thanks.

**Pull request merged**
