### PR TITLE
Add templates from openshift/origin.

### PR DESCRIPTION
**Pull request by pvalena**
WIP, because I'm not sure whether to use json or yaml.

### CODE REVIEW

**Comment by pvalena** [comment]
PTAL.

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
@praiskup Any idea why the rhel CI is failing?

**Comment by praiskup** [comment]
Nope, better logging is needed :/ how it comes that only this PR is affected?

**Comment by praiskup** [comment]
I'll take a look.

**Comment by pkubatrh** [comment]
Thanks I havent been able to reproduce this myself. Although I do not think anything in this PR should influence any of the tests...

**Comment by praiskup** [comment]
In postgresql-container/pull/192 the script was killed at some point.

**Comment by praiskup** [comment]
[test]

**Comment by praiskup** [comment]
$ diff /home/praiskup/rh/projects/openshift-origin/examples/db-templates/postgresql-ephemeral-template.json examples/postgresql-ephemeral-template.json
$ diff /home/praiskup/rh/projects/openshift-origin/examples/db-templates/postgresql-persistent-template.json examples/postgresql-persistent-template.json

I'm not sure how the new symlink is used, but otherwise LGTM.

**Pull request merged**
