### PR TITLE
Remove brew repositories from postgresql 10

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by praiskup** [comment]
looks good, thanks

**Comment by praiskup** [comment]
Well, shouldn't `NOT_RELEASED_VERSIONS = 10` be empty now?

**Comment by pkubatrh** [comment]
>Well, shouldn't NOT_RELEASED_VERSIONS = 10 be empty now?

Fixed, thanks.

Also it seemed like the rhel CI is having some repository issues

**Comment by praiskup** [comment]
Also have a look at #279

**Comment by praiskup** [comment]
lgtm

**Comment by pkubatrh** [comment]
I guess centos rpms for postgresql 10 are not yet rebuilt?

**Comment by pkubatrh** [comment]
Removed the changes to centos repositories

**Comment by praiskup** [comment]
Ok, lgtm

**Comment by praiskup** [comment]
[test][test-openshift]

**Pull request merged**
