### PR TITLE
Update imagestreams for RHEL 8.4

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by phracek** [comment]
As far as I know, we are supporting even versions `postgresql-13`.
 Am I right @hhorak @pkubatrh?

Do we plan to add Postgresql 13 here?

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by hhorak** [comment]
> As far as I know, we are supporting even versions `postgresql-13`.
> Am I right @hhorak @pkubatrh?
> 
> Do we plan to add Postgresql 13 here?

Just confirming PostgreSQL 13 image is already available in the catalog, as it was part of RHEL 8.4 content.

**Review by phracek — APPROVED** [review]
LGTM

**Pull request merged**
