### PR TITLE
Fix templates according to `openshift/origin`

### PR DESCRIPTION
**Pull request by pvalena**
[Replace 'template.openshift.io' with 'openshift.io'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86819501)
 
and 

[Remove ' (Persistent)'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86940496)

### CODE REVIEW

**Comment by pkubatrh** [comment]
From the linked review it seems the template namespace was not used in live Openshift templates, so LGTM.

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test]

**Comment by pvalena** [comment]
Thanks!

**Pull request merged**
