### PR TITLE
Sync with downstream

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by praiskup** [comment]
Nit, what does mean "Sync with downstream" :-).  Otherwise looks good.

**Comment by pkubatrh** [comment]
Ah right, I have created the commit with a general enough name since for some images there have been multiple changes made. But for postgresql only the repository enablement is changed so I have modified the message accordingly.

**Comment by praiskup** [comment]
lgtm

**Comment by pkubatrh** [comment]
Thanks for review, merging.

**Pull request merged**
